version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
  build:
    commands:
      - echo Build started on `date`
      - cp deployments/event_subscriber/production/appspec.yml .
      - ls
  post_build:
    commands:
      - echo Build completed on `date`
      - printf '[{"name":"%s","imageUri":"%s"}]' "$EnvironmentName" "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG" > images.json

artifacts:
  files:
    - '**/*'
  base-directory: '.'